### ISSUE TITLE
[FEATURE] 서버 세팅 

### ISSUE THREAD

**Issue by KangJuHyeon** [KangJuHyeon/coffeeChatbot#1]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: 서버 세팅

### TODO
1. [ ] nestjs 새 프로젝트 만들기
2. [ ] coffeeChatBot CRUD
3. [ ] TypeORM으로 DB 연결
4. [ ] GCP(VM)에 서버 띄우기
