### ISSUE TITLE
[FEATURE] 서버 세팅

### ISSUE THREAD

**Issue by KangJuHyeon** [KangJuHyeon/coffeeChatbot#1]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail:  서버 세팅

### TODO
1. [x] nestjs 서버 세팅
2. [x] coffeeChatbot CRUD 작성
3. [x] TypeORM을 DB와 연결
4. [x] GCP(VM)에 서버 띄우기
